name: ctware
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flare_flutter: ^3.0.2
  fl_chart: ^0.68.0
  carousel_slider: ^4.2.1
  syncfusion_flutter_charts: ^26.2.9
  intl: ^0.19.0
  month_year_picker: ^0.4.0+1
  dio: ^5.7.0
  provider: ^6.1.2
  quickalert: ^1.1.0
  shared_preferences: ^2.3.2
  animated_splash_screen: ^1.3.0
  url_launcher: ^6.3.0
  iconsax: ^0.0.8
  google_maps_flutter: ^2.9.0
  rss_dart: ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/fonts/
      - assets/icons/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-BoldItalic.ttf

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf